#!/bin/bash

script_dir="$(echo "$0" | sed "s/$(basename "$0")//g")"
cache_file="$script_dir../.data"

# If we don't have a cache yet, load it!
if [[ ! -f "$cache_file" ]]; then
  "${script_dir}../src/data" >> "$cache_file"
fi

# Output the result
cat "$cache_file"
