#!/bin/bash
#
# This script will fetch the data as defined by the
# ../src/data file and write it to our cache file
# if it has not already been cached.
#
# This command will then output the location of
# the cache file
##################################################

script_dir=$(dirname "$0")
cache_file="$script_dir/../.data"

# If we don't have a cache yet, load it!
if [[ ! -f "$cache_file" ]]; then
  "${script_dir}/../src/data" >> "$cache_file"
fi

# Output the result
echo "$cache_file"
