#!/usr/bin/env node

// fetch JSON data
const data = { "data": [ {
    "title": "Post 1",
    "date": "Jan 1, 2017",
    "content": "OMG did it's so lite, it's like being on a diet!"
  }, {
    "title": "Post 2",
    "date": "Jan 2, 2017",
    "content": "This can be whatever you want."
  }
]};

console.log(JSON.stringify(data));
