#!/usr/bin/env node

var pug = require('pug');
var fs = require('fs');
var readline = require('readline');

var data;
var tpl = process.argv[2];
var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

rl.on('line', (input) => {
  data = input
});

rl.on('close', () => {
  data = JSON.parse(data)
  for (var post in data.data) {
    post = data.data[post]
    fs.writeFileSync(`public/posts/${post.title.toLowerCase().replace(' ', '-')}.html`, pug.renderFile(tpl, post));
  };
});
