#!/usr/bin/env node
var pug = require('pug');
var fs = require('fs');
var readline = require('readline');

/**
 * Reads the data passed in from stdin, wraps it up into
 * an object and calls compile
 */
function readStdin() {
  var data = '';
  readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
  }).on('line', (input) => {
    data += input;
  }).on('close', () => {
    compile(JSON.parse(data));
  });
}

/**
 * Responsible for compiling all custom pages
 */
function compile(data) {
  compileContributors(data.contributors);
}

/**
 * Creates all of our individual contributor pages
 */
function compileContributors(contributors) {
  // Make dir in public
  var dir = 'public/contributors'
  if (!fs.existsSync(dir)) fs.mkdirSync(dir);

  // Create each contributor page
  for (var contributor of contributors) {
    fs.writeFileSync(
      `${dir}/${contributor.login}.html`,
      pug.renderFile('src/html/templates/contributor.pug', contributor)
    );
  }
}

// Start
readStdin()
